### ISSUE TITLE
Login/SignUp page UI/UX

### ISSUE THREAD

**Issue by Vineetg2003** [Counselllor/Counsellor-Mobile#1]
I want to make a UI/UX of Login/Sign Up page for counsellor app . I have attached some backened code also.

@thestarsahil Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@thestarsahil Sir please assign me these issue

**Comment by dotjson01** [comment]
It's already Done !
Try Something else

**Comment by Vineetg2003** [comment]
ok thanks
