### ISSUE TITLE
UI/UX of Application form for an Counsellor App

### ISSUE THREAD

**Issue by Vineetg2003** [Counselllor/Counsellor-Mobile#2]
I will make UI/UX of Application form for Counsellor form where we can collect information for counsellor app . I will also some attached the backend code.

@thestarsahil Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@thestarsahil Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@thestarsahil Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@thestarsahil ?

**Comment by dotjson01** [comment]
Sounds Good !
Work on Data, Collecting The information from User and Intergrate to Firebase 
Our Web Repo is intergrated with Firebase , So that will be easy
As such same user can open the Web portal and App
